---
run:
  timeout: 3m
linters:
  disable-all: true
  enable:
    - asciicheck
    - deadcode
    - depguard
    - dupl
    - errcheck
    - exhaustive
    - exportloopref
    - funlen
    - goconst
    - gocritic
    - goheader
    - gofmt
    - gosimple
    - govet
    - lll
    - megacheck
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace
linters-settings:
  funlen:
    lines: 188
    statements: 60
  lll:
    line-length: 98
