
ignoreGeneratedHeader = false
severity = "error"
confidence = 0.8
errorCode = 1
warningCode = 0

[directive.specify-disable-reason]

[rule.blank-imports]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.exported]
[rule.if-return]
[rule.increment-decrement]
[rule.var-naming]
  arguments = [["UID", "GID"]]
[rule.var-declaration]
[rule.package-comments]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.errorf]
[rule.empty-block]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]

[rule.atomic]
[rule.bool-literal-in-expr]
[rule.constant-logical-expr]
[rule.unnecessary-stmt]
[rule.unused-receiver]
[rule.get-return]
[rule.flag-parameter]
[rule.confusing-results]
[rule.confusing-naming]
[rule.modifies-parameter]
[rule.modifies-value-receiver]
[rule.import-shadowing]
[rule.range-val-in-closure]
[rule.waitgroup-by-value]
[rule.call-to-gc]
[rule.duplicated-imports]

[rule.argument-limit]
  arguments = [7]
[rule.function-result-limit]
  arguments = [3]

[rule.unhandled-error]
  # functions to ignore unhandled errors on
  arguments = ["fmt.Printf", "fmt.Println"]

# kubebuilder's (apparently bogus!) use of ,inline all over the place
# breaks this rule. So while ideally nice to have I'd rather err on the
# side of k8s tooling. Even if it is a cargo cult :-P
#[rule.struct-tag]

[rule.line-length-limit]
  # I'd ideally prefer 80 but some go idoms make lines a bit longer and
  # not everyone probably loves to line break as much as me :-)
  arguments =[98]
