# permissions for end users to view smbcommonconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbcommonconfig-viewer-role
rules:
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbcommonconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbcommonconfigs/status
  verbs:
  - get
