# permissions for end users to view smbpvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbpvc-viewer-role
rules:
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbpvcs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbpvcs/status
  verbs:
  - get
