# permissions for end users to edit smbpvcs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbpvc-editor-role
rules:
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbpvcs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbpvcs/status
  verbs:
  - get
