# permissions for end users to view smbservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbservice-viewer-role
rules:
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbservices
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbservices/status
  verbs:
  - get
