# permissions for end users to edit smbsecurityconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbsecurityconfig-editor-role
rules:
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbsecurityconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbsecurityconfigs/status
  verbs:
  - get
