# permissions for end users to view smbsecurityconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbsecurityconfig-viewer-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbsecurityconfigs/status
    verbs:
      - get
