# permissions for end users to edit smbservices.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbservice-editor-role
rules:
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - samba-operator.samba.org
  resources:
  - smbservices/status
  verbs:
  - get
