# permissions for end users to edit smbshares.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: smbshare-editor-role
rules:
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - samba-operator.samba.org
    resources:
      - smbshares/status
    verbs:
      - get
