//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbCommonConfig) DeepCopyInto(out *SmbCommonConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbCommonConfig.
func (in *SmbCommonConfig) DeepCopy() *SmbCommonConfig {
	if in == nil {
		return nil
	}
	out := new(SmbCommonConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmbCommonConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbCommonConfigList) DeepCopyInto(out *SmbCommonConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SmbCommonConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbCommonConfigList.
func (in *SmbCommonConfigList) DeepCopy() *SmbCommonConfigList {
	if in == nil {
		return nil
	}
	out := new(SmbCommonConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmbCommonConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbCommonConfigPodSettings) DeepCopyInto(out *SmbCommonConfigPodSettings) {
	*out = *in
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(v1.Affinity)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbCommonConfigPodSettings.
func (in *SmbCommonConfigPodSettings) DeepCopy() *SmbCommonConfigPodSettings {
	if in == nil {
		return nil
	}
	out := new(SmbCommonConfigPodSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbCommonConfigSpec) DeepCopyInto(out *SmbCommonConfigSpec) {
	*out = *in
	out.Network = in.Network
	if in.PodSettings != nil {
		in, out := &in.PodSettings, &out.PodSettings
		*out = new(SmbCommonConfigPodSettings)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbCommonConfigSpec.
func (in *SmbCommonConfigSpec) DeepCopy() *SmbCommonConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SmbCommonConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbCommonConfigStatus) DeepCopyInto(out *SmbCommonConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbCommonConfigStatus.
func (in *SmbCommonConfigStatus) DeepCopy() *SmbCommonConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SmbCommonConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbCommonNetworkSpec) DeepCopyInto(out *SmbCommonNetworkSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbCommonNetworkSpec.
func (in *SmbCommonNetworkSpec) DeepCopy() *SmbCommonNetworkSpec {
	if in == nil {
		return nil
	}
	out := new(SmbCommonNetworkSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSecurityConfig) DeepCopyInto(out *SmbSecurityConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSecurityConfig.
func (in *SmbSecurityConfig) DeepCopy() *SmbSecurityConfig {
	if in == nil {
		return nil
	}
	out := new(SmbSecurityConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmbSecurityConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSecurityConfigList) DeepCopyInto(out *SmbSecurityConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SmbSecurityConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSecurityConfigList.
func (in *SmbSecurityConfigList) DeepCopy() *SmbSecurityConfigList {
	if in == nil {
		return nil
	}
	out := new(SmbSecurityConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmbSecurityConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSecurityConfigSpec) DeepCopyInto(out *SmbSecurityConfigSpec) {
	*out = *in
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = new(SmbSecurityUsersSpec)
		**out = **in
	}
	if in.JoinSources != nil {
		in, out := &in.JoinSources, &out.JoinSources
		*out = make([]SmbSecurityJoinSpec, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Domains != nil {
		in, out := &in.Domains, &out.Domains
		*out = make([]SmbSecurityDomainSpec, len(*in))
		copy(*out, *in)
	}
	if in.DNS != nil {
		in, out := &in.DNS, &out.DNS
		*out = new(SmbSecurityDNSSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSecurityConfigSpec.
func (in *SmbSecurityConfigSpec) DeepCopy() *SmbSecurityConfigSpec {
	if in == nil {
		return nil
	}
	out := new(SmbSecurityConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSecurityConfigStatus) DeepCopyInto(out *SmbSecurityConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSecurityConfigStatus.
func (in *SmbSecurityConfigStatus) DeepCopy() *SmbSecurityConfigStatus {
	if in == nil {
		return nil
	}
	out := new(SmbSecurityConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSecurityDNSSpec) DeepCopyInto(out *SmbSecurityDNSSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSecurityDNSSpec.
func (in *SmbSecurityDNSSpec) DeepCopy() *SmbSecurityDNSSpec {
	if in == nil {
		return nil
	}
	out := new(SmbSecurityDNSSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSecurityDomainSpec) DeepCopyInto(out *SmbSecurityDomainSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSecurityDomainSpec.
func (in *SmbSecurityDomainSpec) DeepCopy() *SmbSecurityDomainSpec {
	if in == nil {
		return nil
	}
	out := new(SmbSecurityDomainSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSecurityJoinSpec) DeepCopyInto(out *SmbSecurityJoinSpec) {
	*out = *in
	if in.UserJoin != nil {
		in, out := &in.UserJoin, &out.UserJoin
		*out = new(SmbSecurityUserJoinSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSecurityJoinSpec.
func (in *SmbSecurityJoinSpec) DeepCopy() *SmbSecurityJoinSpec {
	if in == nil {
		return nil
	}
	out := new(SmbSecurityJoinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSecurityUserJoinSpec) DeepCopyInto(out *SmbSecurityUserJoinSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSecurityUserJoinSpec.
func (in *SmbSecurityUserJoinSpec) DeepCopy() *SmbSecurityUserJoinSpec {
	if in == nil {
		return nil
	}
	out := new(SmbSecurityUserJoinSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSecurityUsersSpec) DeepCopyInto(out *SmbSecurityUsersSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSecurityUsersSpec.
func (in *SmbSecurityUsersSpec) DeepCopy() *SmbSecurityUsersSpec {
	if in == nil {
		return nil
	}
	out := new(SmbSecurityUsersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbShare) DeepCopyInto(out *SmbShare) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbShare.
func (in *SmbShare) DeepCopy() *SmbShare {
	if in == nil {
		return nil
	}
	out := new(SmbShare)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmbShare) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbShareList) DeepCopyInto(out *SmbShareList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SmbShare, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbShareList.
func (in *SmbShareList) DeepCopy() *SmbShareList {
	if in == nil {
		return nil
	}
	out := new(SmbShareList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmbShareList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbSharePvcSpec) DeepCopyInto(out *SmbSharePvcSpec) {
	*out = *in
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbSharePvcSpec.
func (in *SmbSharePvcSpec) DeepCopy() *SmbSharePvcSpec {
	if in == nil {
		return nil
	}
	out := new(SmbSharePvcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbShareScalingSpec) DeepCopyInto(out *SmbShareScalingSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbShareScalingSpec.
func (in *SmbShareScalingSpec) DeepCopy() *SmbShareScalingSpec {
	if in == nil {
		return nil
	}
	out := new(SmbShareScalingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbShareSpec) DeepCopyInto(out *SmbShareSpec) {
	*out = *in
	in.Storage.DeepCopyInto(&out.Storage)
	if in.Scaling != nil {
		in, out := &in.Scaling, &out.Scaling
		*out = new(SmbShareScalingSpec)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbShareSpec.
func (in *SmbShareSpec) DeepCopy() *SmbShareSpec {
	if in == nil {
		return nil
	}
	out := new(SmbShareSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbShareStatus) DeepCopyInto(out *SmbShareStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbShareStatus.
func (in *SmbShareStatus) DeepCopy() *SmbShareStatus {
	if in == nil {
		return nil
	}
	out := new(SmbShareStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbShareStorageSpec) DeepCopyInto(out *SmbShareStorageSpec) {
	*out = *in
	if in.Pvc != nil {
		in, out := &in.Pvc, &out.Pvc
		*out = new(SmbSharePvcSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbShareStorageSpec.
func (in *SmbShareStorageSpec) DeepCopy() *SmbShareStorageSpec {
	if in == nil {
		return nil
	}
	out := new(SmbShareStorageSpec)
	in.DeepCopyInto(out)
	return out
}
