// +build !ignore_autogenerated

// Code generated by operator-sdk-v0.17.1. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbPvc) DeepCopyInto(out *SmbPvc) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbPvc.
func (in *SmbPvc) DeepCopy() *SmbPvc {
	if in == nil {
		return nil
	}
	out := new(SmbPvc)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmbPvc) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbPvcList) DeepCopyInto(out *SmbPvcList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SmbPvc, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbPvcList.
func (in *SmbPvcList) DeepCopy() *SmbPvcList {
	if in == nil {
		return nil
	}
	out := new(SmbPvcList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SmbPvcList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbPvcSpec) DeepCopyInto(out *SmbPvcSpec) {
	*out = *in
	if in.Pvc != nil {
		in, out := &in.Pvc, &out.Pvc
		*out = new(v1.PersistentVolumeClaimSpec)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbPvcSpec.
func (in *SmbPvcSpec) DeepCopy() *SmbPvcSpec {
	if in == nil {
		return nil
	}
	out := new(SmbPvcSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SmbPvcStatus) DeepCopyInto(out *SmbPvcStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SmbPvcStatus.
func (in *SmbPvcStatus) DeepCopy() *SmbPvcStatus {
	if in == nil {
		return nil
	}
	out := new(SmbPvcStatus)
	in.DeepCopyInto(out)
	return out
}
